### PR TITLE
Bump sassc version and depend on sassc ~> 1.3

### PR DESCRIPTION
**Pull request by edward**
@bolandrm

### CODE REVIEW

**Comment by bolandrm** [comment]
@edward looks like the color hex codes changed case

**Comment by bolandrm** [comment]
to be clear, this is changing the MINOR version dependency.  i.e. allowing any minor version that is above the one currently specified.  I think that's fine though.

**Comment by edward** [comment]
> @edward looks like the color hex codes changed case

Interesting! Is this ok? Should be ok, right?

**Comment by edward** [comment]
> to be clear, this is changing the MINOR version dependency. i.e. allowing any minor version that is above the one currently specified. I think that's fine though.

Yep, you’re right – we’re allowing versions of `sassc` >= 1.3.0 and < 2.0.0

I’ll correct the title here. My bad.

**Pull request merged**
